<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701151117 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, commentaire TEXT DEFAULT NULL, date_evaluation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, auteur_id INT NOT NULL, cible_id INT NOT NULL, trajet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1323A57560BB6FE6 ON evaluation (auteur_id)');
        $this->addSql('CREATE INDEX IDX_1323A575A96E5E09 ON evaluation (cible_id)');
        $this->addSql('CREATE INDEX IDX_1323A575D12A823 ON evaluation (trajet_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, est_lu BOOLEAN NOT NULL, date_lu TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type_message VARCHAR(20) DEFAULT NULL, expediteur_id INT NOT NULL, destinataire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F10335F61 ON message (expediteur_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FA4F84F6E ON message (destinataire_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, places_reservees INT NOT NULL, prix_total DOUBLE PRECISION DEFAULT NULL, statut VARCHAR(20) NOT NULL, date_reservation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_confirmation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_annulation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motif_annulation TEXT DEFAULT NULL, passager_id INT NOT NULL, trajet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C8495571A51189 ON reservation (passager_id)');
        $this->addSql('CREATE INDEX IDX_42C84955D12A823 ON reservation (trajet_id)');
        $this->addSql('CREATE TABLE trajet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ville_depart VARCHAR(100) NOT NULL, ville_arrivee VARCHAR(100) NOT NULL, quartier_depart VARCHAR(100) NOT NULL, point_depart VARCHAR(100) NOT NULL, point_arrivee VARCHAR(100) NOT NULL, quartier_retour VARCHAR(100) DEFAULT NULL, date_depart TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_depart TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, places_disponibles INT NOT NULL, prix_par_place DOUBLE PRECISION NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, conducteur_id INT NOT NULL, vehicule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B5BA98CF16F4AC6 ON trajet (conducteur_id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98C4A4A3511 ON trajet (vehicule_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, mot_de_passe VARCHAR(255) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, type_utilisateur VARCHAR(20) DEFAULT NULL, photo VARCHAR(255) DEFAULT NULL, biographie TEXT DEFAULT NULL, preferences_voyage JSON DEFAULT NULL, note_moyenne DOUBLE PRECISION DEFAULT NULL, est_actif BOOLEAN NOT NULL, roles JSON NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql('CREATE TABLE vehicule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, marque VARCHAR(30) NOT NULL, modele VARCHAR(30) NOT NULL, couleur VARCHAR(20) NOT NULL, plaque_immatriculation VARCHAR(30) NOT NULL, places INT NOT NULL, photo VARCHAR(255) DEFAULT NULL, est_defaut BOOLEAN NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_292FFF1DFB88E14F ON vehicule (utilisateur_id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57560BB6FE6 FOREIGN KEY (auteur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575A96E5E09 FOREIGN KEY (cible_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575D12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F10335F61 FOREIGN KEY (expediteur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FA4F84F6E FOREIGN KEY (destinataire_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495571A51189 FOREIGN KEY (passager_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955D12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id)');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98CF16F4AC6 FOREIGN KEY (conducteur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98C4A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id)');
        $this->addSql('ALTER TABLE vehicule ADD CONSTRAINT FK_292FFF1DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A57560BB6FE6');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575A96E5E09');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575D12A823');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F10335F61');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FA4F84F6E');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495571A51189');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955D12A823');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98CF16F4AC6');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98C4A4A3511');
        $this->addSql('ALTER TABLE vehicule DROP CONSTRAINT FK_292FFF1DFB88E14F');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE trajet');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE vehicule');
    }
}
