<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260807125942 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE confirmation_presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, est_present BOOLEAN NOT NULL, confirme_par_conducteur BOOLEAN DEFAULT NULL, gps_verifie BOOLEAN DEFAULT NULL, timestamp_confirmation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trajet_id INT NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B93CBC6D12A823 ON confirmation_presence (trajet_id)');
        $this->addSql('CREATE INDEX IDX_9B93CBC6FB88E14F ON confirmation_presence (utilisateur_id)');
        $this->addSql('CREATE TABLE position_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, vitesse DOUBLE PRECISION DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, trajet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B44B61B8FB88E14F ON position_history (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_B44B61B8D12A823 ON position_history (trajet_id)');
        $this->addSql('CREATE INDEX idx_position_timestamp ON position_history (timestamp)');
        $this->addSql('ALTER TABLE confirmation_presence ADD CONSTRAINT FK_9B93CBC6D12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id)');
        $this->addSql('ALTER TABLE confirmation_presence ADD CONSTRAINT FK_9B93CBC6FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE position_history ADD CONSTRAINT FK_B44B61B8FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_history ADD CONSTRAINT FK_B44B61B8D12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation ALTER commission TYPE DOUBLE PRECISION');
        $this->addSql('ALTER TABLE reservation ALTER commission DROP DEFAULT');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT fk_2b5ba98cf3966caa');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT fk_2b5ba98c3dd2084');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT fk_2b5ba98cc16565fc');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT fk_2b5ba98cbf9a3ff6');
        $this->addSql('DROP INDEX idx_2b5ba98cbf9a3ff6');
        $this->addSql('DROP INDEX idx_2b5ba98c3dd2084');
        $this->addSql('DROP INDEX idx_2b5ba98cf3966caa');
        $this->addSql('DROP INDEX idx_2b5ba98cc16565fc');
        $this->addSql('ALTER TABLE trajet ADD point_depart_lat DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_depart_lng DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_arrivee_lat DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_arrivee_lng DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD position_actuelle_lat DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD position_actuelle_lng DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD trajet_active BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE trajet ADD heure_arrivee_estimee TIME(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet DROP quartier_retour');
        $this->addSql('ALTER TABLE trajet DROP lieu_depart_id');
        $this->addSql('ALTER TABLE trajet DROP lieu_arrivee_id');
        $this->addSql('ALTER TABLE trajet DROP point_depart_lieu_id');
        $this->addSql('ALTER TABLE trajet DROP point_arrivee_lieu_id');
        $this->addSql('ALTER TABLE vehicule DROP photo');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE confirmation_presence DROP CONSTRAINT FK_9B93CBC6D12A823');
        $this->addSql('ALTER TABLE confirmation_presence DROP CONSTRAINT FK_9B93CBC6FB88E14F');
        $this->addSql('ALTER TABLE position_history DROP CONSTRAINT FK_B44B61B8FB88E14F');
        $this->addSql('ALTER TABLE position_history DROP CONSTRAINT FK_B44B61B8D12A823');
        $this->addSql('DROP TABLE confirmation_presence');
        $this->addSql('DROP TABLE position_history');
        $this->addSql('ALTER TABLE reservation ALTER commission TYPE INT');
        $this->addSql('ALTER TABLE reservation ALTER commission SET DEFAULT 0');
        $this->addSql('ALTER TABLE trajet ADD quartier_retour VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD lieu_depart_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD lieu_arrivee_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_depart_lieu_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_arrivee_lieu_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet DROP point_depart_lat');
        $this->addSql('ALTER TABLE trajet DROP point_depart_lng');
        $this->addSql('ALTER TABLE trajet DROP point_arrivee_lat');
        $this->addSql('ALTER TABLE trajet DROP point_arrivee_lng');
        $this->addSql('ALTER TABLE trajet DROP position_actuelle_lat');
        $this->addSql('ALTER TABLE trajet DROP position_actuelle_lng');
        $this->addSql('ALTER TABLE trajet DROP trajet_active');
        $this->addSql('ALTER TABLE trajet DROP heure_arrivee_estimee');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT fk_2b5ba98cf3966caa FOREIGN KEY (point_arrivee_lieu_id) REFERENCES lieu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT fk_2b5ba98c3dd2084 FOREIGN KEY (point_depart_lieu_id) REFERENCES lieu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT fk_2b5ba98cc16565fc FOREIGN KEY (lieu_depart_id) REFERENCES lieu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT fk_2b5ba98cbf9a3ff6 FOREIGN KEY (lieu_arrivee_id) REFERENCES lieu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_2b5ba98cbf9a3ff6 ON trajet (lieu_arrivee_id)');
        $this->addSql('CREATE INDEX idx_2b5ba98c3dd2084 ON trajet (point_depart_lieu_id)');
        $this->addSql('CREATE INDEX idx_2b5ba98cf3966caa ON trajet (point_arrivee_lieu_id)');
        $this->addSql('CREATE INDEX idx_2b5ba98cc16565fc ON trajet (lieu_depart_id)');
        $this->addSql('ALTER TABLE vehicule ADD photo VARCHAR(255) DEFAULT NULL');
    }
}
