<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702160613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lieu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(30) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, code_postal VARCHAR(20) DEFAULT NULL, region VARCHAR(50) DEFAULT NULL, departement VARCHAR(50) DEFAULT NULL, pays VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, est_actif BOOLEAN NOT NULL, est_principal BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, lieu_parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F577D591D1D51C7 ON lieu (lieu_parent_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) NOT NULL, message TEXT NOT NULL, type VARCHAR(30) NOT NULL, est_lu BOOLEAN NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_lecture TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, icone VARCHAR(50) DEFAULT NULL, couleur VARCHAR(20) DEFAULT NULL, destinataire_id INT NOT NULL, trajet_id INT DEFAULT NULL, reservation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA4F84F6E ON notification (destinataire_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAD12A823 ON notification (trajet_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAB83297E7 ON notification (reservation_id)');
        $this->addSql('CREATE TABLE paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant DOUBLE PRECISION NOT NULL, reference VARCHAR(100) NOT NULL, moyen_paiement VARCHAR(30) NOT NULL, statut VARCHAR(30) NOT NULL, date_paiement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_confirmation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_remboursement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, code_transaction VARCHAR(50) DEFAULT NULL, numero_transaction VARCHAR(50) DEFAULT NULL, message_erreur TEXT DEFAULT NULL, reservation_id INT NOT NULL, passager_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1DC7A1EAEA34913 ON paiement (reference)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B1DC7A1EB83297E7 ON paiement (reservation_id)');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E71A51189 ON paiement (passager_id)');
        $this->addSql('ALTER TABLE lieu ADD CONSTRAINT FK_2F577D591D1D51C7 FOREIGN KEY (lieu_parent_id) REFERENCES lieu (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA4F84F6E FOREIGN KEY (destinataire_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAD12A823 FOREIGN KEY (trajet_id) REFERENCES trajet (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E71A51189 FOREIGN KEY (passager_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT fk_1323a575d12a823');
        $this->addSql('DROP INDEX idx_1323a575d12a823');
        $this->addSql('ALTER TABLE evaluation RENAME COLUMN trajet_id TO reservation_id');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id)');
        $this->addSql('CREATE INDEX IDX_1323A575B83297E7 ON evaluation (reservation_id)');
        $this->addSql('ALTER TABLE trajet ADD lieu_depart_id INT NOT NULL');
        $this->addSql('ALTER TABLE trajet ADD lieu_arrivee_id INT NOT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_depart_lieu_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD point_arrivee_lieu_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98CC16565FC FOREIGN KEY (lieu_depart_id) REFERENCES lieu (id)');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98CBF9A3FF6 FOREIGN KEY (lieu_arrivee_id) REFERENCES lieu (id)');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98C3DD2084 FOREIGN KEY (point_depart_lieu_id) REFERENCES lieu (id)');
        $this->addSql('ALTER TABLE trajet ADD CONSTRAINT FK_2B5BA98CF3966CAA FOREIGN KEY (point_arrivee_lieu_id) REFERENCES lieu (id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98CC16565FC ON trajet (lieu_depart_id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98CBF9A3FF6 ON trajet (lieu_arrivee_id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98C3DD2084 ON trajet (point_depart_lieu_id)');
        $this->addSql('CREATE INDEX IDX_2B5BA98CF3966CAA ON trajet (point_arrivee_lieu_id)');
        $this->addSql('ALTER TABLE utilisateur ADD ville_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3A73F0036 FOREIGN KEY (ville_id) REFERENCES lieu (id)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3A73F0036 ON utilisateur (ville_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lieu DROP CONSTRAINT FK_2F577D591D1D51C7');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA4F84F6E');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAD12A823');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAB83297E7');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1EB83297E7');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E71A51189');
        $this->addSql('DROP TABLE lieu');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('ALTER TABLE evaluation DROP CONSTRAINT FK_1323A575B83297E7');
        $this->addSql('DROP INDEX IDX_1323A575B83297E7');
        $this->addSql('ALTER TABLE evaluation RENAME COLUMN reservation_id TO trajet_id');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT fk_1323a575d12a823 FOREIGN KEY (trajet_id) REFERENCES trajet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_1323a575d12a823 ON evaluation (trajet_id)');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98CC16565FC');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98CBF9A3FF6');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98C3DD2084');
        $this->addSql('ALTER TABLE trajet DROP CONSTRAINT FK_2B5BA98CF3966CAA');
        $this->addSql('DROP INDEX IDX_2B5BA98CC16565FC');
        $this->addSql('DROP INDEX IDX_2B5BA98CBF9A3FF6');
        $this->addSql('DROP INDEX IDX_2B5BA98C3DD2084');
        $this->addSql('DROP INDEX IDX_2B5BA98CF3966CAA');
        $this->addSql('ALTER TABLE trajet DROP lieu_depart_id');
        $this->addSql('ALTER TABLE trajet DROP lieu_arrivee_id');
        $this->addSql('ALTER TABLE trajet DROP point_depart_lieu_id');
        $this->addSql('ALTER TABLE trajet DROP point_arrivee_lieu_id');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3A73F0036');
        $this->addSql('DROP INDEX IDX_1D1C63B3A73F0036');
        $this->addSql('ALTER TABLE utilisateur DROP ville_id');
    }
}
