<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute type/revele et colonnes nullable sur evaluation, crée et seed la table plafond_prix';
    }

    public function up(Schema $schema): void
    {
        // --- Evaluation : type (CONDUCTEUR/PASSAGER/PLATEFORME) + révélateur double-aveugle ---
        $this->addSql('ALTER TABLE evaluation ADD type VARCHAR(20) DEFAULT \'CONDUCTEUR\' NOT NULL');
        $this->addSql('ALTER TABLE evaluation ADD revele BOOLEAN DEFAULT false NOT NULL');

        // Les évaluations PLATEFORME n'ont ni cible, ni réservation, ni trajet.
        $this->addSql('ALTER TABLE evaluation ALTER COLUMN cible_id DROP NOT NULL');
        $this->addSql('ALTER TABLE evaluation ALTER COLUMN reservation_id DROP NOT NULL');
        $this->addSql('ALTER TABLE evaluation ALTER COLUMN trajet_id DROP NOT NULL');

        // --- Table des plafonds de prix (FCFA) par paire de villes ---
        $this->addSql('CREATE TABLE plafond_prix (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ville_depart VARCHAR(100) NOT NULL, ville_arrivee VARCHAR(100) NOT NULL, prix_max DOUBLE PRECISION NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PLAFOND_V1 ON plafond_prix (ville_depart, ville_arrivee)');
        $this->addSql('CREATE INDEX IDX_PLAFOND_DEPART ON plafond_prix (ville_depart)');
        $this->addSql('CREATE INDEX IDX_PLAFOND_ARRIVEE ON plafond_prix (ville_arrivee)');

        // --- Seed : prix maximum conseillés (covoiturage) sur les grands axes du Cameroun ---
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Douala\', 5000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Yaoundé\', 5000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Bafoussam\', 6500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Bafoussam\', \'Yaoundé\', 6500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Bafoussam\', 5500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Bafoussam\', \'Douala\', 5500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Bamenda\', 9000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Bamenda\', \'Douala\', 9000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Bamenda\', 9000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Bamenda\', \'Yaoundé\', 9000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Garoua\', 15000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Garoua\', \'Douala\', 15000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Garoua\', 15000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Garoua\', \'Yaoundé\', 15000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Maroua\', 17000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Maroua\', \'Douala\', 17000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Maroua\', 17000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Maroua\', \'Yaoundé\', 17000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Kribi\', 2500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Kribi\', \'Douala\', 2500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Kribi\', 3000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Kribi\', \'Yaoundé\', 3000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Limbé\', 2000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Limbé\', \'Douala\', 2000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Bertoua\', 8000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Bertoua\', \'Yaoundé\', 8000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Douala\', \'Edéa\', 1500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Edéa\', \'Douala\', 1500, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Yaoundé\', \'Ebolowa\', 4000, CURRENT_TIMESTAMP)');
        $this->addSql('INSERT INTO plafond_prix (ville_depart, ville_arrivee, prix_max, date_creation) VALUES (\'Ebolowa\', \'Yaoundé\', 4000, CURRENT_TIMESTAMP)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DELETE FROM evaluation WHERE type = \'PLATEFORME\' AND cible_id IS NULL');

        $this->addSql('ALTER TABLE evaluation ALTER COLUMN cible_id SET NOT NULL');
        $this->addSql('ALTER TABLE evaluation ALTER COLUMN reservation_id SET NOT NULL');
        $this->addSql('ALTER TABLE evaluation ALTER COLUMN trajet_id SET NOT NULL');

        $this->addSql('ALTER TABLE evaluation DROP type');
        $this->addSql('ALTER TABLE evaluation DROP revele');

        $this->addSql('DROP TABLE plafond_prix');
    }
}
