<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260812043649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE demande_trajet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ville_depart VARCHAR(100) NOT NULL, ville_arrivee VARCHAR(100) NOT NULL, quartier_depart VARCHAR(100) DEFAULT NULL, quartier_arrivee VARCHAR(100) DEFAULT NULL, date_depart DATE NOT NULL, heure_depart TIME(0) WITHOUT TIME ZONE DEFAULT NULL, nb_places INT NOT NULL, budget_max DOUBLE PRECISION NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(30) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_expiration TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prix_propose DOUBLE PRECISION DEFAULT NULL, est_privee BOOLEAN DEFAULT false NOT NULL, passager_id INT NOT NULL, conducteur_acceptant_id INT DEFAULT NULL, destinataire_prive_id INT DEFAULT NULL, trajet_cree_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_691FEF6371A51189 ON demande_trajet (passager_id)');
        $this->addSql('CREATE INDEX IDX_691FEF6339C65F04 ON demande_trajet (conducteur_acceptant_id)');
        $this->addSql('CREATE INDEX IDX_691FEF636F5718FF ON demande_trajet (destinataire_prive_id)');
        $this->addSql('CREATE INDEX IDX_691FEF63D745C796 ON demande_trajet (trajet_cree_id)');
        $this->addSql('CREATE TABLE preference_trajet_conducteur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ville_depart_habituelle VARCHAR(100) NOT NULL, ville_arrivee_habituelle VARCHAR(100) NOT NULL, jours_habituels JSON NOT NULL, budget_minimum DOUBLE PRECISION DEFAULT NULL, notification_active BOOLEAN DEFAULT true NOT NULL, conducteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B5F9421F16F4AC6 ON preference_trajet_conducteur (conducteur_id)');
        $this->addSql('ALTER TABLE demande_trajet ADD CONSTRAINT FK_691FEF6371A51189 FOREIGN KEY (passager_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE demande_trajet ADD CONSTRAINT FK_691FEF6339C65F04 FOREIGN KEY (conducteur_acceptant_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE demande_trajet ADD CONSTRAINT FK_691FEF636F5718FF FOREIGN KEY (destinataire_prive_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE demande_trajet ADD CONSTRAINT FK_691FEF63D745C796 FOREIGN KEY (trajet_cree_id) REFERENCES trajet (id)');
        $this->addSql('ALTER TABLE preference_trajet_conducteur ADD CONSTRAINT FK_9B5F9421F16F4AC6 FOREIGN KEY (conducteur_id) REFERENCES utilisateur (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE demande_trajet DROP CONSTRAINT FK_691FEF6371A51189');
        $this->addSql('ALTER TABLE demande_trajet DROP CONSTRAINT FK_691FEF6339C65F04');
        $this->addSql('ALTER TABLE demande_trajet DROP CONSTRAINT FK_691FEF636F5718FF');
        $this->addSql('ALTER TABLE demande_trajet DROP CONSTRAINT FK_691FEF63D745C796');
        $this->addSql('ALTER TABLE preference_trajet_conducteur DROP CONSTRAINT FK_9B5F9421F16F4AC6');
        $this->addSql('DROP TABLE demande_trajet');
        $this->addSql('DROP TABLE preference_trajet_conducteur');
    }
}
